services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: Vk_Max_bot
    restart: unless-stopped
    volumes:
      - ./logs:/code/logs
      - ./last_id.txt:/code/last_id.txt